# Install Config
api: 2
version: 5
name: Pheonix-Server
author: Prasad T
# Configuration
config:
  # Enabled Tasks
  tasks:
    update: true
    upgrade: true
    # Add Repos
    # individual repos flags are mentioned under config.add_repo key
    repo: true
    # Add PPAs
    ppa: false
    # APT Packages
    apt: true
    # Whether to purge packages mentioned in config.purge key
    purge: true
    debs: false
    pip2: false
    pip3: false
    binaries: false
  # Repository Flags
  add_repo:
    winehq: false
    docker: false
    mendeley: false
    googlecloud: false
    spotify: true
    vscode: true
    skype: false
    signal: false
    insync: false
    google: true
    ros: false
  # Flags
  flags:
  # Simulate flag will never be overridden by remote config.
    purge_enabled: true
    preserve_debs: false
  # Packages to purge
  purge:
    - gnome-mines
    - gnome-sudoku
    - aisleriot
    - gnome-mahjongg
  # Install components
  # APT Packages, Python Modules, Debian packages
  install:
    apt:
      # Admin related Stuff
      administration:
        - dconf-editor
        - htop
        - apt-xapian-index
        - gdebi
        - gparted
        - synaptic
        - bleachbit
        - tree
        - gnome-logs
        - gnome-system-monitor
        - gnome-calculator
        - gnome-usage
      # Security Related Stuff
      security:
        - gufw
      # Productivity & Office Tools.
      productivity:
        - evolution
        - realmd
        - pandoc-data
        - pandoc
        - texstudio
        - texlive-fonts-extra
        - texlive-formats-extra
        - texlive-fonts-recommended
        - texlive-science
        - texlive-xetex
        - texlive-luatex
        - texlive-pstricks
        - texlive-science
        - texlive-extra-utils
        - texlive-lang-english
        - texlive-lang-other
        - texlive-font-utils
        - texlive-publishers
        - gummi
      # Multimedia Tools. Photo Editors Converting tools, plex etc.
      multimedia:
        - audacity
        - vlc
        - gimp
        - handbrake
        - handbrake-cli
        - rawtherapee
        - darktable
        - mpv
        - pavucontrol
        - cheese
      # Tools related to development.
      development:
        - curl
        - spyder3
        - git
        - shellcheck
        - clinfo
        - vainfo
        - vdpauinfo
        - python3-pip
      # Everything Else
      other:
        - evolution
        - gnome-tweaks
        - opensc
        - pcscd
        - scdaemon
        - zsh
        - seahorse-nautilus
        - ccache
        - gcc-opt
        - python3-tk
        - virt-manager
        - virt-viewer
        - libvirt-daemon-system
        - rustc
        - cargo
        - cmake
        - make
        - neovim
        - pass
        - golang-docker-credential-helpers
      external:
        - google-chrome-stable
        - spotify-client
        - code
        - neofetch
        - chromium-browser
        - ubuntu-restricted-extras
        - ubuntu-restricted-addons
        - unrar

